version: '3'
services:
  pgadmin:
    container_name: pg-admin-4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=me@email.com
      - PGADMIN_DEFAULT_PASSWORD=1234567
    ports:
      - 15432:80
    restart: always

  postgres:
    container_name: postgres-docker
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_DB=mydatabase
    ports:
      - 5433:5432
    restart: always

